import { test, expect } from '@playwright/test';

test('successful login', async ({ page }) => {
  await page.goto('https://parabank.parasoft.com/parabank/index.htm;jsessionid=EA791E3729BD3345105040CEC2DCC658');
  await page.getByRole('link', { name: 'Register' }).click();
  await page.locator('[id="customer.firstName"]').click();
  await page.locator('[id="customer.firstName"]').fill('test');
  await page.locator('[id="customer.lastName"]').click();
  await page.locator('[id="customer.lastName"]').fill('playwight');
  await page.locator('[id="customer.address.street"]').click();
  await page.locator('[id="customer.address.street"]').fill('21 igbe lagos');
  await page.locator('[id="customer.address.city"]').click();
  await page.locator('[id="customer.address.city"]').fill('lagos');
  await page.locator('[id="customer.address.state"]').click();
  await page.locator('[id="customer.address.state"]').fill('lagos');
  await page.locator('[id="customer.address.zipCode"]').click();
  await page.locator('[id="customer.address.zipCode"]').fill('123');
  await page.locator('[id="customer.phoneNumber"]').click();
  await page.locator('[id="customer.phoneNumber"]').fill('23481809688');
  await page.locator('[id="customer.ssn"]').click();
  await page.locator('[id="customer.ssn"]').fill('33');
  await page.locator('[id="customer.username"]').click();
  await page.locator('[id="customer.username"]').press('CapsLock');
  await page.locator('[id="customer.username"]').fill('T');
  await page.locator('[id="customer.username"]').press('CapsLock');
  await page.locator('[id="customer.username"]').fill('Teniola');
  await page.locator('[id="customer.password"]').click();
  await page.locator('[id="customer.password"]').press('CapsLock');
  await page.locator('[id="customer.password"]').fill('T');
  await page.locator('[id="customer.password"]').press('CapsLock');
  await page.locator('[id="customer.password"]').fill('Teniola1234@');
  await page.locator('#repeatedPassword').click();
  await page.locator('#repeatedPassword').fill('');
  await page.locator('[id="customer.password"]').click();
  await page.locator('[id="customer.password"]').fill('test1234@');
  await page.locator('#repeatedPassword').click();
  await page.locator('#repeatedPassword').press('CapsLock');
  await page.locator('#repeatedPassword').fill('T');
  await page.locator('#repeatedPassword').press('CapsLock');
  await page.locator('#repeatedPassword').fill('Test1234');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.locator('[id="customer.password"]').click();
  await page.locator('[id="customer.password"]').press('CapsLock');
  await page.locator('[id="customer.password"]').fill('T');
  await page.locator('[id="customer.password"]').press('CapsLock');
  await page.locator('[id="customer.password"]').fill('Test1234@');
  await page.locator('#repeatedPassword').click();
  await page.locator('#repeatedPassword').press('CapsLock');
  await page.locator('#repeatedPassword').fill('T');
  await page.locator('#repeatedPassword').press('CapsLock');
  await page.locator('#repeatedPassword').fill('Test1234@');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('link', { name: 'Open New Account' }).click();
  await page.getByRole('button', { name: 'Open New Account' }).click();
  await page.getByRole('link', { name: 'Accounts Overview' }).click();
  await page.getByRole('link', { name: 'Transfer Funds' }).click();
  await page.locator('#amount').click();
  await page.locator('#amount').fill('150');
  await page.locator('#toAccountId').selectOption('22224');
  await page.getByRole('button', { name: 'Transfer' }).click();
  await page.getByRole('link', { name: 'Transfer Funds' }).click();
  await page.getByRole('link', { name: 'Bill Pay' }).click();
  await page.getByRole('link', { name: 'Find Transactions' }).click();
  await page.getByText('Select an account: 22002 22224 Find by Transaction ID: Find Transactions Find').click();
  await page.locator('#transactionId').click();
  await page.locator('#transactionId').fill('2');
  await page.locator('#transactionDate').click();
  await page.getByRole('link', { name: 'Request Loan' }).click();
  await page.locator('#amount').click();
  await page.locator('#amount').fill('10000');
  await page.locator('#downPayment').click();
  await page.locator('#downPayment').fill('2000');
  await page.getByRole('button', { name: 'Apply Now' }).click();
  await page.goto('https://parabank.parasoft.com/parabank/findtrans.htm');
  await page.getByRole('link', { name: 'Request Loan' }).click();
  await page.locator('#amount').click();
  await page.locator('#amount').fill('100000');
  await page.locator('#downPayment').click();
  await page.locator('#downPayment').fill('1000');
  await page.getByRole('button', { name: 'Apply Now' }).click();
  await page.getByRole('link', { name: 'Admin Page' }).click();
  await page.getByRole('link', { name: 'Log Out' }).click();
  await page.locator('input[name="username"]').click();
  await page.locator('input[name="username"]').press('CapsLock');
  await page.locator('input[name="username"]').fill('T');
  await page.locator('input[name="username"]').press('CapsLock');
  await page.locator('input[name="username"]').fill('Teniola');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').press('CapsLock');
  await page.locator('input[name="password"]').fill('T');
  await page.locator('input[name="password"]').press('CapsLock');
  await page.locator('input[name="password"]').fill('Test1234@');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('link', { name: 'Update Contact Info' }).click();
  await page.getByRole('button', { name: 'Update Profile' }).click();
  await page.getByRole('link', { name: 'Find Transactions' }).click();
  await page.getByRole('link', { name: 'Request Loan' }).click();
  await page.locator('#amount').click();
  await page.locator('#amount').fill('100000');
  await page.locator('#downPayment').click();
  await page.locator('#downPayment').fill('200');
  await page.getByRole('button', { name: 'Apply Now' }).click();
  await page.locator('body').click();
  await expect(page.getByRole('link', { name: 'Open New Account' })).toBeVisible();
  await page.getByRole('link', { name: 'Open New Account' }).click();
  await expect(page.getByRole('link', { name: 'Bill Pay' })).toBeVisible();
  await page.getByRole('link', { name: 'Accounts Overview' }).click();
});